Repository njallskarp/finetune-qa-powerset, pull requests merged in 2023-06, with the labels that each got.

#19 Feature/adding main file
  main.py
  training/metrics.py
  training_datasets/__init__.py
Labels: enhancement

#22 bugfix/imported evaluate model
  training/validate.py
Labels: bug

#27 Update lint.yml
  .github/workflows/lint.yml
Labels: enhancement

#28 # syncing dev <--> main
  .github/workflows/lint.yml
Labels: enhancement

#29 Added tokenizers package to dependencies
  poetry.lock
  pyproject.toml
Labels: enhancement

#31 Feat/training-datasets (encodings)
  training_datasets/__init__.py
  training_datasets/datasets.py
Labels: enhancement

#33 Chore/improve codescore
  main.py
  training/metrics.py
  training/train.py
  training/validate.py
  types/declarations.py
Labels: documentation

#35 Added black to devDependencies
  poetry.lock
  pyproject.toml
Labels: enhancement

#37 Update lint.yml, Black
  .github/workflows/lint.yml
Labels: enhancement

#38 Applied black to codebase
  main.py
  training/metrics.py
  training/train.py
  training/utils.py
  training/validate.py
  types/declarations.py
Labels: enhancement

#42 Yaml should now take into account formatting changes
  .github/workflows/lint.yml
Labels: bug

#43 Loading model function made and refactored for more concise code
  models/models.py
  training/utils.py
  training_datasets/datasets.py
Labels: enhancement
